Diploma/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Diploma.Models;
using Diploma.Models.ViewModels;
using Diploma.Services;
using Microsoft.AspNet.Identity;

namespace Diploma.Controllers
{
    public class HomeController : Controller
    {
        private readonly IApplicationService _applicationService;

        public HomeController(IApplicationService applicationService)
        {
            _applicationService = applicationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LeaveMessage(LeaveMessageViewModel leaveMessageViewModel)
        {
            if (ModelState.IsValid) {
                var userId = User.Identity.GetUserId();

                leaveMessageViewModel.UserId = userId;

                await _applicationService.LeaveMessage(leaveMessageViewModel);

                ViewBag.Message = "Thank you for your message!\n We`ll contact you in 24 hours.";
            }

            return View("Contact");
        }

        public IActionResult Error(ErrorViewModel errorViewModel)
        {
            return View(errorViewModel);
        }
    }
}

Diploma/Controllers/RouteInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Diploma.Models;
using Diploma.Models.Entities;
using Diploma.Models.Enums;
using Diploma.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNet.Identity;

namespace Diploma.Controllers
{
    [Authorize]
    public class RouteInfoesController : Controller
    {
        private readonly ApplicationContext _context;

        public RouteInfoesController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> GetAvailableRoutesList()
        {
            var currentUserId = User.Identity.GetUserId();

            var appliedUserRouteInfoesId = await GetUserAppliedRoutesIds();

            var routeInfoesList = await _context.RouteInfo
                .Include(context => context.User)
                .Include(context => context.Route)
                .Where(routeInfo => routeInfo.User.Id != currentUserId
                        && routeInfo.IsDriver == true
                        && !appliedUserRouteInfoesId.Contains(routeInfo.Route.Id))
                .ToListAsync();

            return View("Index", routeInfoesList);
        }

        private async Task<List<Guid>> GetUserAppliedRoutesIds()
        {
            var currentUserId = User.Identity.GetUserId();

            var appliedUserRouteInfoesId = await _context.RouteInfo
                .Include(context => context.User)
                .Include(context => context.Route)
                .Where(routeInfo => routeInfo.User.Id == currentUserId
                        && routeInfo.IsPassenger == true)
                 .Select(item => item.Route.Id)
                .ToListAsync();

            return appliedUserRouteInfoesId;
        }

        public async Task<IActionResult> GetUserAppliedRoutesList()
        {
            var appliedUserRouteInfoesId = await GetUserAppliedRoutesIds();

            var appliedUserRouteInfoesList = await _context.RouteInfo
                .Include(context => context.User)
                .Include(context => context.Route)
                .Where(routeInfo => appliedUserRouteInfoesId.Contains(routeInfo.Route.Id)
                                    && routeInfo.IsPassenger == true)
                .ToListAsync();

            return View("UserAppliedRoutes", appliedUserRouteInfoesList);
        }

        public async Task<IActionResult> GetUserCreatedRoutesList()
        {
            var currentUserId = User.Identity.GetUserId();

            var userRouteInfoesList = await _context.RouteInfo
                .Include(context => context.User)
                .Include(context => context.Route)
                .Where(routeInfo => routeInfo.User.Id == currentUserId
                        && routeInfo.IsDriver == true
                        && routeInfo.RouteApplicationStatus != RouteApplicationStatus.Cancelled)
                .ToListAsync();

            return View("UserCreatedRoutes", userRouteInfoesList);
        }

        public async Task<IActionResult> ApplyForRoute(Guid? routeId)
        {
            var currentUserId = User.Identity.GetUserId();
            var currentUser = _context.Users.FirstOrDefault(user => user.Id == currentUserId);

            var appliedRoute = _context.Routes.FirstOrDefault(route => route.Id == routeId);

            var routeInfo = new RouteInfo
            {
                IsPassenger = true,
                User = currentUser,
                Route = appliedRoute,
                RouteApplicationStatus = RouteApplicationStatus.Pending
            };

            _context.RouteInfo.Add(routeInfo);
            await _context.SaveChangesAsync();

            return RedirectToAction("GetUserAppliedRoutesList");
        }

        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var routeInfo = await _context.RouteInfo
                .Include(context => context.User)
                .Include(context => context.Route)
                .SingleOrDefaultAsync(routeInfoItem => routeInfoItem.Id == id);

            if (routeInfo == null)
            {
                return NotFound();
            }

            var routeDetailsViewModel = new RouteDetailsViewModel
            {
                RouteInfo = routeInfo,
                AvailablePlaces = routeInfo.Route.Capacity - await GetCountOfAppliedUsers(routeInfo.Route.Id),
                PassengersApplications = await GetPassengersRouteApplicationsList(routeInfo.Route.Id)
            };  

            return View(routeDetailsViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateRouteViewModel addRouteViewModel)
        {
            if (ModelState.IsValid)
            {
                var currentUserId = User.Identity.GetUserId();
                var currentUser = _context.Users.FirstOrDefault(user => user.Id == currentUserId);

                var route = new Route
                {
                    Currency = addRouteViewModel.Currency,
                    From = addRouteViewModel.From,
                    To = addRouteViewModel.To,
                    RouteLength = addRouteViewModel.RouteLength.Value,
                    Price = addRouteViewModel.Price,
                    RouteStatus = RouteStatus.Pending,
                    Capacity = addRouteViewModel.Capacity,
                    Comment = addRouteViewModel.Comment,
                    DepartureTime = new DateTime(addRouteViewModel.DepartureDate.Year,
                        addRouteViewModel.DepartureDate.Month, addRouteViewModel.DepartureDate.Day,
                        addRouteViewModel.DepartureTime.Hour, addRouteViewModel.DepartureTime.Minute, 0)
                };

                var routeInfo = new RouteInfo
                {
                    User = currentUser,
                    IsDriver = true,
                    Route = route
                };

                _context.Add(routeInfo);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index", "Home");
            }
            return View(addRouteViewModel);
        }

        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var routeInfo = await _context.RouteInfo
                .Include(item => item.Route)
                .Include(item => item.User)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (routeInfo == null)
            {
                return NotFound();
            }

            var currentUserId = User.Identity.GetUserId();

            if (routeInfo.User.Id != currentUserId)
            {
                return View("Error", new ErrorViewModel{ErrorMessage = "You can`t edit not your route!"});
            }

            return View(routeInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassengerApplicationStatus(Guid userId, Guid routeId, RouteApplicationStatus routeApplicationStatus)
        {
            var routeInfo = await _context.RouteInfo
                .Include(item => item.User)
                .Include(item => item.Route)
                .Where(item => item.Route.Id == routeId
                               && item.User.Id == userId.ToString()).SingleAsync();

            routeInfo.RouteApplicationStatus = routeApplicationStatus;

            await _context.SaveChangesAsync();
            
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, RouteInfo routeInfo)
        {
            if (id != routeInfo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(routeInfo);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RouteInfoExists(routeInfo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(routeInfo);
        }

        public async Task<IActionResult> Cancel(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var routeInfo = await _context.RouteInfo
                .SingleOrDefaultAsync(m => m.Id == id);
            if (routeInfo == null)
            {
                return NotFound();
            }

            return View(routeInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Cancel(Guid id)
        {
            var routeInfo = await _context.RouteInfo
                .Include(item => item.User)
                .Include(item => item.Route)
                .SingleOrDefaultAsync(m => m.Id == id);

            var currentUserId = User.Identity.GetUserId();

            if (routeInfo.User.Id != currentUserId)
            {
                return View("Error", new ErrorViewModel { ErrorMessage = "You can`t delete not your route!" });
            }

            var countOfAppliedUsers = await GetCountOfAppliedUsers(routeInfo.Route.Id);

Diploma/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>

<p>Taras Shevchenko National University of Kiev, 2018.</p>

Diploma/Views/Home/Contact.cshtml
@model Diploma.Models.ViewModels.LeaveMessageViewModel

@{
    ViewData["Title"] = "Contact";
}

<h2>@ViewData["Title"]</h2>

<address>
    Kiev, Sechienova 6, 16 dormitory
</address>

<address>
    <strong>Support:</strong> <a href="mailto:yehor.chernyshenko@gmail.com">yehor.chernyshenko@gmail.com</a><br />
</address>

<div class="row">
    <div class="col-md-4">
        <form asp-controller="Home" asp-action="LeaveMessage">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @if (string.IsNullOrEmpty(ViewBag.Message))
            {
                if (!User.Identity.IsAuthenticated) {
                     <div class="form-group">
                         <label asp-for="Email" class="control-label"></label>
                         <input asp-for="Email" class="form-control"/>
                         <span asp-validation-for="Email" class="text-danger"></span>
                     </div>
                     <div class="form-group">
                         <label asp-for="PhoneNumber" class="control-label"></label>
                         <input asp-for="PhoneNumber" class="form-control"/>
                         <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                     </div>
                 }

                <div class="form-group">
                    <label asp-for="Message" class="control-label"></label>
                    <input asp-for="Message" class="form-control"/>
                    <span asp-validation-for="Message" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Leave message" class="btn btn-default"/>
                </div>
            } else {
                <h4 style="color:green;">@ViewBag.Message</h4>
            }

        </form>
    </div>
</div>

Diploma/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@if (User.Identity.IsAuthenticated)
{
    <p>Hello, @User.Identity.Name!</p>
    
    <a asp-controller="Account" asp-action="AccountDetails">Account Details</a>
    <br>
    <a asp-controller="RouteInfoes" asp-action="GetAvailableRoutesList">List of available routes</a>
    <br>
    <a asp-controller="RouteInfoes" asp-action="GetUserCreatedRoutesList">Your created routes</a>
    <br>
    <a asp-controller="RouteInfoes" asp-action="GetUserAppliedRoutesList">Your applied routes</a>
    <br>
    <a asp-controller="RouteInfoes" asp-action="Create">Create new route</a>
    <br>
    <form method="post" asp-controller="Account" asp-action="LogOff">
        <input type="submit" value="Log Off" />
    </form>
}